### ISSUE TITLE
--blame show offending commit

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#485]
In cunjunction with the --diff option, it would be useful to know when the lint message was introduced.

```
./scalafix-nightly -r DisableSyntax --config-str="DisableSyntax.keywords=[var]" --diff-base="HEAD~10"
/home/gui/scalafix/scalafix-core/shared/src/main/scala/scalafix/internal/util/IntervalSet.scala:31:11: error: [DisableSyntax.keywords.var] keywords.var is disabled
          var i = start
          ^
/home/gui/scalafix/scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliGitDiffTests.scala:224:13: error: [DisableSyntax.keywords.var] keywords.var is disabled
    private var revision = 0
            ^
```

```
./scalafix-nightly -r DisableSyntax --config-str="DisableSyntax.keywords=[var]" --blame --diff-base="HEAD~10"
b5ba2c1e8 (Guillaume Massé 2017-12-06 14:01:18 +0100 31)
/home/gui/scalafix/scalafix-core/shared/src/main/scala/scalafix/internal/util/IntervalSet.scala:31:11: error: [DisableSyntax.keywords.var] keywords.var is disabled
          var i = start
          ^
f4e0e3c10 (Guillaume Massé 2017-12-04 11:57:02 +0100 224)
/home/gui/scalafix/scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliGitDiffTests.scala:224:13: error: [DisableSyntax.keywords.var] keywords.var is disabled
    private var revision = 0
            ^
```

`git blame HEAD~10..HEAD path`

**Comment by MasseGuillaume** [comment]
I'm on this.

**Comment by olafurpg** [comment]
This feature ended up getting reverted in #855. The reason to revert the change is that I think it's outside the scope of the project. External tools are able to compute the same blame metadata from the position information, there is nothing inherent that requires this information to be computed inside the core scalafix engine.
