### ISSUE TITLE
Scalafix can't parse context bounds in polymorphic functions added in Scala 3.6.3

### ISSUE THREAD

**Issue by mrdziuban** [scalacenter/scalafix#2182]
Using the new context bounds for polymorphic functions feature added in Scala 3.6.3 (https://github.com/scala/scala3/pull/21643) like this:

```scala
val test: [A: Numeric] => A => Int = [A: Numeric] => _.toInt
```

results in an error in Scalafix:

```scala
/Users/matt/Desktop/test.scala:1:11: error: `identifier` expected but `[` found
val test: [A: Numeric] => A => Int = [A: Numeric] => _.toInt
          ^
```

**Comment by tgodzik** [comment]
Looks like it works in the newest scalameta, it should also work for scalafix, though maybe it needs a new release? This might have been fixed recently

**Comment by bjaglin** [comment]
Thanks for the report @mrdziuban ! Same as @tgodzik though, I can't reproduce, neither with 0.14.0 nor on the latest SNAPSHOT.

Maybe you use an outdated Scalafix version (< 0.14.0)? Or you or your build tool runs scalafix without passing the scala version, resulting in an attempt to parse source with a Scala 2 dialect?

**Comment by mrdziuban** [comment]
Ahh sorry for the false report, I think I was based off of a branch using scalafix 0.13.0 at the time 🤦‍♂  I can confirm it works with 0.14.0, thanks for looking into it!
