### PR TITLE
Add --blame to show offending commit of Diagnostic (fix #485)

### LINKED ISSUE #485: --blame show offending commit
In cunjunction with the --diff option, it would be useful to know when the lint message was introduced.

```
./scalafix-nightly -r DisableSyntax --config-str="DisableSyntax.keywords=[var]" --diff-base="HEAD~10"
/home/gui/scalafix/scalafix-core/shared/src/main/scala/scalafix/internal/util/IntervalSet.scala:31:11: error: [DisableSyntax.keywords.var] keywords.var is disabled
          var i = start
          ^
/home/gui/scalafix/scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliGitDiffTests.scala:224:13: error: [DisableSyntax.keywords.var] keywords.var is disabled
    private var revision = 0
            ^
```

```
./scalafix-nightly -r DisableSyntax --config-str="DisableSyntax.keywords=[var]" --blame --diff-base="HEAD~10"
b5ba2c1e8 (Guillaume Massé 2017-12-06 14:01:18 +0100 31)
/home/gui/scalafix/scalafix-core/shared/src/main/scala/scalafix/internal/util/IntervalSet.scala:31:11: error: [DisableSyntax.keywords.var] keywords.var is disabled
          var i = start
          ^
f4e0e3c10 (Guillaume Massé 2017-12-04 11:57:02 +0100 224)
/home/gui/scalafix/scalafix-tests/unit/src/test/scala/scalafix/tests/cli/CliGitDiffTests.scala:224:13: error: [DisableSyntax.keywords.var] keywords.var is disabled
    private var revision = 0
            ^
```

`git blame HEAD~10..HEAD path`

### PR DESCRIPTION
**Pull request by MasseGuillaume**
Example output:

commit message: r0

```scala
object Code {
  val a = 42
}
```

commit message: r1

```scala
object Code {
  var a = 42
}
```

```
/tmp/scalafix1367068904944601960/code.scala:2:3: error: [DisableSyntax.keywords.var] 
2018-08-31 12:01 Guillaume Massé e27e0825 - r1
var is disabled
  var a = 42
  ^^^
```

### CODE REVIEW

File: scalafix-cli/src/main/scala/scalafix/internal/jgit/JGitBlame.scala [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+    blameGenerator.push("", repository.resolve(startRev))
+    val blameResult = BlameResult.create(blameGenerator)
+    diagnostics.foreach(
+      diagnostic =>
+        blameResult.computeRange(
+          diagnostic.position.startLine,
+          diagnostic.position.startLine + 1))
+    val lintsWithBlame =
+      diagnostics.map { diagnostic =>
+        val line = diagnostic.position.startLine
```
Comment (MasseGuillaume) [inline scalafix-cli/src/main/scala/scalafix/internal/jgit/JGitBlame.scala]: To simplify the problem, I only take the `startLine`.

File: scalafix-cli/src/main/scala/scalafix/internal/jgit/JGitBlame.scala [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+    val date = dateFormat.format(author.getWhen)
+    s"$date $authorName $shortSha - $commitMsg"
+  }
+
+  private def blame(
+      filePath: Path,
+      diagnostics: List[RuleDiagnostic]): List[RuleDiagnostic] = {
+    val blameGenerator = new BlameGenerator(repository, filePath.toString)
+    val startRev = diffBase.getOrElse(Constants.HEAD)
+    blameGenerator.push("", repository.resolve(startRev))
```
Comment (MasseGuillaume) [inline scalafix-cli/src/main/scala/scalafix/internal/jgit/JGitBlame.scala]: This works with `--diff-base`, it will start from the startrev, it can be any git magic (`HEAD~100`, etc).

File: scalafix-cli/src/main/scala/scalafix/internal/jgit/JGitBlame.scala [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+
+import org.eclipse.jgit.revwalk.RevCommit
+
+class JGitBlame(workingDir: Path, diffBase: Option[String]) {
+  private val builder = new FileRepositoryBuilder()
+  private val repository =
+    builder.readEnvironment().setWorkTree(workingDir.toFile).build()
+  private val dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm")
+
+  def apply(diagnostics: List[RuleDiagnostic]): List[RuleDiagnostic] = {
```
Comment (olafurpg) [inline scalafix-cli/src/main/scala/scalafix/internal/jgit/JGitBlame.scala]: You already have access to the nio.Path file in `unsafeHandleFile`
```
  def unsafeHandleFile(args: ValidatedArgs, file: AbsolutePath): ExitStatus = {
```

That would avoid the `val path = ...` match below.

File: scalafix-cli/src/main/scala/scalafix/internal/v1/MainOps.scala [hunk 4]
```diff
@@ -198,7 +199,13 @@ object MainOps {
       }
 
     if (!args.args.autoSuppressLinterErrors) {
```
Comment (olafurpg) [inline scalafix-cli/src/main/scala/scalafix/internal/v1/MainOps.scala]: Can we move this whole if block into a separate method `handlePathDiagnostics`? The method is already big enough.

File: scalafix-cli/src/main/scala/scalafix/internal/jgit/JGitBlame.scala [hunk 5]
```diff
@@ -0,0 +1,89 @@
...
+
+    val diagnosticsByFilePath: List[(Path, List[RuleDiagnostic])] =
+      diagnostics.groupBy { diagnostic =>
```
Comment (olafurpg) [inline scalafix-cli/src/main/scala/scalafix/internal/jgit/JGitBlame.scala]: Is there a case where there are multiple unique `path`? `unsafeHandleFile` processes one file at a time so you're guaranteed there will only be a single file.

File: scalafix-cli/src/main/scala/scalafix/internal/jgit/JGitBlame.scala [hunk 6]
```diff
@@ -0,0 +1,89 @@
...
+      diagnostics.map { diagnostic =>
+        val line = diagnostic.position.startLine
+        val commit = blameResult.getSourceCommit(line)
+        val blameLine = formatCommit(commit)
+
+        val diag = diagnostic.diagnostic
+        RuleDiagnostic(
+          Diagnostic(
+            diag.categoryID,
+            "\n" + blameLine + "\n" + diag.message,
```
Comment (olafurpg) [inline scalafix-cli/src/main/scala/scalafix/internal/jgit/JGitBlame.scala]: I think it would be better to leave formatting to the reporter, the same way `categoryID` and `severity` handled. Let's add a `ScalafixDiagnosticBlame` interface to scalafix-interfaces and add `blame: Option[DiagnosticBlame]]` method to `RuleDiagnostic`. This formatting decision here can then move to `PrintStreamReporter`.

`DiagnosticBlame` doesn't need to be a case class, it can instead compute the values on-demand via methods like:

- date
- authorName
- shortSha
- commitMsg

and other useful information you can think of.

**Comment by gabro** [comment]
This is really cool!

Minor suggestion to improve readability (at the cost of console space):

```
/tmp/scalafix1367068904944601960/code.scala:2:3: error: [DisableSyntax.keywords.var] 
var is disabled

  var a = 42
  ^^^

Introduced by Guillaume Massé on 2018-08-31 12:01 in commit e27e0825 - r1
```

**Comment by MasseGuillaume** [comment]
```
/tmp/scalafix5140789664660253329/code.scala:2:3: error: [DisableSyntax.keywords.var] var is disabled

Introduced by Guillaume Massé on 2018-09-03 11:39 in commit f1ed13fe - r1
  var a = 42
  ^^^

```
