### ISSUE TITLE
empty line in for comprehension sometime doesn't not compile since v0.13.0

### ISSUE THREAD

**Issue by strokyl** [scalacenter/scalafix#2089]
After the update to v0.13.0, when running scalafix, we have a lot of compilation errors with the following message:
```
error: `}` expected but `<-` found
```
Normal scala compilation works fine.
The only common pattern I found where this occurs is that an empty line always precedes the problematic line.
But where it gets weird is that I have some for comprehension with empty lines that compile fine with scalafix.

Here is an example:
```scala
    for {
      maybeOrg     <- findOrganization
      organization <- ZIO.succeed(maybeOrg).someOrElseZIO(createOrganization(consoleConfig.organization))

      (maybeAdminUser, otherUsers) <-
        syncLocalUsers(
          adminUserConfig = consoleConfig.admin,
          otherUserConfigs = consoleConfig.auth.map(_.localUsers).getOrElse(Nil),
          organizationId = organization.id
        )

      _                            <- maybeAdminUser
                                        .map(adminUser => addUserToOrganizationService.addUserToOrganization(adminUser.email, organization.id, isAdmin = true))
                                        .getOrElse(ZIO.unit)
      _                            <- ZIO.foreachDiscard(otherUsers)(user =>
                                        addUserToOrganizationService.addUserToOrganization(user.email, organization.id, isAdmin = false)
                                      )

      _ <- maybeAdminUser.map(adminUser => initializeClusters(organization, adminUser)).getOrElse(ZIO.unit)

    } yield ()
```

the scala error is:
```
[info] Running scalafix on 1 Scala sources (incremental)
[error] /home/lduzan/code/console-plus-2/modules/admin/admin/src/main/scala/io/conduktor/admin/service/OnPremInitializationService.scala:44:36: error: `}` expected but `<-` found
[error]       _                            <- maybeAdminUser
[error]                                    ^^
[error] (Compile / scalafix) scalafix.sbt.ScalafixFailed: ParseError
[error] Total time: 0 s, completed 30 sept. 2024, 10:20:26
```
and removing the empty line before `maybeAdminUser` fixes the issue.

scala version: 3.5.1
scalafix version: 0.13.0
sbt version: 1.10.2

**Comment by bjaglin** [comment]
If you don't beat me to it, I'll do it later today.

**Comment by bjaglin** [comment]
Looks like it's already done https://github.com/scalameta/scalameta/issues/3979

**Comment by bjaglin** [comment]
The fix above was merged in scalameta. As soon as a release is cut (probably a matter of ~weeks), we'll be able to bump it and confirm the fix is working via [Scalafix SNAPSHOTs](https://scalacenter.github.io/scalafix/docs/users/installation.html#snapshot).

**Comment by bjaglin** [comment]
upcoming snapshot should fix the problem thanks to https://github.com/scalacenter/scalafix/pull/2103
